FROM balenalib/raspberrypi4-64:bullseye

RUN apt-get update
ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get install -y git cmake gcc-aarch64-linux-gnu \
    libsdl2-dev \
    libopencv-dev \
    python3 \
    libtinfo-dev \
    zlib1g-dev \
    build-essential \
    libedit-dev \
    libxml2-dev \
    libopenblas-dev \
    liblapack-dev \
    gzip

ADD . mukham

RUN mkdir mukham/build

ADD ./build.sh mukham/build/

WORKDIR mukham/build

RUN cmake ..

CMD ["/bin/bash", "-c", "build.sh"]
