name: Linux Build

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Deps
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y libsdl2-dev
          sudo apt-get install -y libopencv-dev python3-opencv

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}


