name: Linux Build

on: workflow_dispatch

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Deps
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y libsdl2-dev
          sudo apt-get install -y libopencv-dev python3-opencv
          sudo apt-get install python3 python3-pip build-essential python-dev

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Convert models
        run: |
          python3 --version
          pip3 install tlcpack-nightly -f https://tlcpack.ai/wheels
          pip3 install tflite==2.1.0 --user
          cd scripts
          python3 convert_blazeface.py
          python3 convert_facemesh.py

      - name: Build
        run: |
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          tar -zcvf ${{github.workspace}}/mukham.tar.gz ${{github.workspace}}/build/bin


