name: Raspberry PI 4 Build

on:
  push

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Deps
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y qemu-user-static
          sudo apt-get install -y binfmt-support

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build Docker image
        run: docker build --no-cache -t mukham-pi4 -f docker/Dockerfile.pi4 .

      - name: Build mukham
        run: docker run --rm -v $PWD/mukham.pi4.tar.gz:/mukham/build/mukham.pi4.tar.gz mukham-pi4

      - name: Release
        uses: actions/create_release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: mukham
          tag_name: nightly
          body_path: Readme.md

      - name: Upload pi4 binaries
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./mukham.pi4.tar.gz
          asset_name: mukham.pi4.tar.gz
          asset_content_type: application/gzip


