name: Release Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{matrix.os}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install Deps
        if : matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update -y -qq
          sudo apt-get install -y libsdl2-dev
          sudo apt-get install -y libopencv-dev python3-opencv
          sudo apt-get install python3.8 python3-pip build-essential python-dev
          python3 --version
          pip3 install tlcpack-nightly -f https://tlcpack.ai/wheels
          pip3 install tflite==2.1.0 --user

      - name: Install Deps - windows
        if: matrix.os == 'windows-latest'
        run: |
          choco install opencv
          choco install curl
          choco install cmake
          choco install python3 --version=3.8.10
          choco install 7zip
          curl -O https://www.libsdl.org/release/SDL2-devel-2.0.20-VC.zip
          7z x SDL2-devel-2.0.20-VC.zip -oc:/tools/SDL2
          cp sdl2-config.cmake C:/tools/SDL2/SDL2-2.0.20/
          Get-ChildItem C:/tools/opencv/build/x64 -recurse
          Get-ChildItem C:/tools/SDL2 -recurse
          py --list
          py -3.8 -m pip install tlcpack-nightly -f https://tlcpack.ai/wheels
          py -3.8 -m pip install tflite==2.1.0 --user

      - name: Convert models - Linux
        if : matrix.os == 'ubuntu-latest'
        run: |
          cd scripts
          python3 convert_blazeface.py
          python3 convert_facemesh.py

      - name: Convert models - Windows
        if: matrix.os == 'windows-latest'
        run: |
          cd scripts
          py -3.8 convert_blazeface.py
          py -3.8 convert_facemesh.py

      - name: Linux Build
        if : matrix.os == 'ubuntu-latest'
        run: |
          cmake -B build -Wno-dev -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build build --config ${{env.BUILD_TYPE}}
          tar -zcvf mukham-linux-x64.tar.gz build/bin
          ls

      - name: Windows Build
        if : matrix.os == 'windows-latest'
        env:
          SDL2_DIR: C:/tools/SDL2/SDL2-2.0.20
          OpenCV_DIR: C:/tools/opencv/build
        run: |
          cmake -B build -Wno-dev -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build build --config ${{env.BUILD_TYPE}}
          copy C:/tools/opencv/build/x64/vc15/bin/*.dll build/bin/Release
          copy C:/tools/SDL2/SDL2-2.0.20/lib/x64/*.dll build/bin/Release
          7z a mukham-win-x64.zip build/bin/*
          Get-ChildItem .

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          path: |
            mukham-win-x64.zip
            mukham-linux-x64.tar.gz

  release:
    name: "Release"
    needs: build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/download-artifact@v2

      - name: Display artifacts
        run: ls -l -R

      - name: Github release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            artifact/mukham-linux-x64.tar.gz
            artifact/mukham-win-x64.zip

