name: Windows Build

on: workflow_dispatch

env:
  BUILD_TYPE: Release
  SDL2_DIR: C:/tools/SDL2/SDL2-2.0.20
  OpenCV_DIR: C:/tools/opencv/build

jobs:
  build:
      runs-on: windows-2019

      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install OpenCV
        run: choco install opencv

      - name: Install SDL
        run: |
          choco install curl
          curl -O https://www.libsdl.org/release/SDL2-devel-2.0.20-VC.zip
          choco install 7zip
          7z x SDL2-devel-2.0.20-VC.zip -oc:/tools/SDL2
          cp sdl2-config.cmake C:/tools/SDL2/SDL2-2.0.20/

      - name: Check paths
        run: |
          Get-ChildItem C:/tools/opencv/build/x64 -recurse
          Get-ChildItem C:/tools/SDL2 -recurse

      - name: Install cmake
        run: choco install cmake

      - name: Build mukham
        run: |
          mkdir build
          cd build
          cmake -Wno-dev ..
          cmake --build . --target ALL_BUILD --config Release
          7z a mukham-win-x64.zip bin/*

      - name: Release
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            *.zip
