name: Windows Build

on: push

env:
  BUILD_TYPE: Release

jobs:
  build:
      runs-on: windows-2019

      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install OpenCV
        run: choco install opencv

      - name: Install SDL
        run: |
          choco install curl
          curl -O https://www.libsdl.org/release/SDL2-devel-2.0.20-VC.zip
          choco install 7zip
          7z x SDL2-devel-2.0.20-VC.zip -oc:/tools/SDL2
          cp sdl2-config.cmake C:/tools/SDL2/SDL2-2.0.20/

      - name: Check paths
        run: |
          dir c:/tools
          dir c:/tools/SDL2
          dir c:/tools/SDL2/SDL2-2.0.20
          dir *.txt

      - name: Install cmake
        run: choco install cmake

      - name: Build mukham
        run: |
          mkdir build
          cd build
          set SDL2_DIR=C:/tools/SDL2/SDL2-2.0.20
          set OpenCV_DIR=C:/tools/opencv/build
          cmake ..
          cmake --build .
