name: Windows Build

on: workflow_dispatch

env:
  BUILD_TYPE: Release
  SDL2_DIR: C:/tools/SDL2/SDL2-2.0.20
  OpenCV_DIR: C:/tools/opencv/build

jobs:
  build:
      runs-on: windows-2019

      steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Install OpenCV
        run: choco install opencv

      - name: Install SDL
        run: |
          choco install curl
          curl -O https://www.libsdl.org/release/SDL2-devel-2.0.20-VC.zip
          choco install 7zip
          7z x SDL2-devel-2.0.20-VC.zip -oc:/tools/SDL2
          cp sdl2-config.cmake C:/tools/SDL2/SDL2-2.0.20/

      - name: Check paths
        run: |
          Get-ChildItem C:/tools/opencv/build/x64 -recurse
          Get-ChildItem C:/tools/SDL2 -recurse

      - name: Install cmake
        run: choco install cmake

      - name: Convert models
        run: |
          choco install python3 --version=3.8.10
          pip install tlcpack-nightly -f https://tlcpack.ai/wheels
          pip install tflite==2.1.0 --user
          cd scripts
          python convert_blazeface.py
          python convert_facemesh.py

      - name: Build mukham
        run: |
          cmake -B ${{github.workspace}}/build -Wno-dev -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}
          copy C:/tools/opencv/build/x64/vc15/bin/*.dll ${{github.workspace}}/build/bin/
          copy C:/tools/SDL2/SDL2-2.0.20/lib/x64/*.dll ${{github.workspace}}/build/bin/
          7z a mukham-win-x64.zip ${{github.workspace}}/build/bin/*
